"""Noise generators for the joint denoise+extend task (T11 §2/§3).

T11 changes the INPUT assumption: the VPU input is NOT a clean band-limited
signal — the target device has noise across ALL frequencies, speech
concentrated below ~500 Hz (real metro operating-point SNR ~10–14 dB at
100–400 Hz, PRIVATE review; T11 §3's 5 dB was a STRESS-TEST point, NOT the
operating point), plus possibly strong WIND noise.  Wind is the
worst case because it is low-frequency-dominated and overlaps the only usable
speech band.

Three noise types, each independently generatable + unit-testable (§5.8):
  * white — flat-spectrum Gaussian (the easy baseline).
  * wind  — low-freq spectral ramp (−slope dB/oct above a corner) + slow
            amplitude modulation (gusts).  Low-freq-dominated ⇒ overlaps speech.
  * body  — transient decaying bursts (impacts/friction); moved here from
            degradation.py so all noise types share one module.

`scale_to_speech_band_snr` mixes noise under a clean-ish speech signal so the
SNR measured IN the speech band hits a target (0/5/10/20 dB sweep).  口径 (T11):
the noise is added to the INPUT (sensor); the TARGET stays the clean ref mic.
"""
from __future__ import annotations

import numpy as np
import torch


def white_noise(T: int, sr: float, rng: np.random.Generator) -> np.ndarray:
    """Flat-spectrum Gaussian noise, unit std, float32 (T,)."""
    return rng.standard_normal(T).astype(np.float32)


def wind_noise(T: int, sr: float, rng: np.random.Generator,
               slope_dboct: float = 15.0, corner_hz: float = 30.0,
               gust_rate_hz: float = 1.0, gust_depth: float = 0.5) -> np.ndarray:
    """Low-freq-dominated wind noise.

    Spectrum: flat below ``corner_hz``, then −slope_dboct dB/oct above (a
    low-freq ramp).  Low-freq-dominated ⇒ overlaps the 50–150 Hz speech/F0
    region (the worst case).  Plus slow amplitude modulation (gusts):
    multiply by (1 + gust_depth·sin(2π·gust_rate·t)) for non-stationarity.

    Generated by shaping white noise in the frequency domain (rfft → ramp →
    irfft), then the time-domain AM.
    """
    w = rng.standard_normal(T).astype(np.float32)
    # spectral ramp
    n = T
    freqs = np.fft.rfftfreq(n, 1 / sr)
    gain_db = np.where(freqs > corner_hz,
                       -slope_dboct * np.log2(np.maximum(freqs / corner_hz, 1e-12)),
                       0.0)
    gain = 10.0 ** (gain_db / 20.0)
    spec = np.fft.rfft(w)
    shaped = np.fft.irfft(spec * gain, n=n).astype(np.float32)
    # slow amplitude modulation (gusts) — independent phase per call
    t = np.arange(n, dtype=np.float32) / sr
    am = 1.0 + gust_depth * np.sin(2 * np.pi * gust_rate_hz * t
                                    + rng.uniform(0, 2 * np.pi))
    return shaped * am


def body_noise(T: int, sr: float, rng: np.random.Generator,
               n_impacts: int = 3, amp_range=(0.05, 0.3),
               decay_ms=(50, 300)) -> np.ndarray:
    """Transient body-conduction noise: decaying bursts (impacts/friction)."""
    out = np.zeros(T, dtype=np.float32)
    for _ in range(n_impacts):
        pos = int(rng.integers(0, T))
        amp = float(rng.uniform(*amp_range))
        decay = float(rng.uniform(*decay_ms)) * 1e-3 * sr   # samples
        length = min(int(sr * 0.05), T - pos)
        if length > 0:
            env = np.exp(-np.arange(length, dtype=np.float32) / decay)
            out[pos:pos + length] += amp * env * rng.standard_normal(length).astype(np.float32)
    return out


def speech_band_power(wav: np.ndarray, sr: float,
                      band=(50.0, 977.0), n_fft: int = 2048) -> float:
    """Mean power (|STFT|^2 averaged) in the speech band."""
    if len(wav) < n_fft:
        wav = np.pad(wav, (0, n_fft - len(wav)))
    hop = n_fft // 2
    n = 1 + (len(wav) - n_fft) // hop
    win = np.hanning(n_fft)
    acc = np.zeros(n_fft // 2 + 1)
    for i in range(n):
        sp = np.abs(np.fft.rfft(wav[i * hop:i * hop + n_fft] * win, n_fft)) ** 2
        acc += sp
    acc /= max(n, 1)
    freqs = np.fft.rfftfreq(n_fft, 1 / sr)
    m = (freqs >= band[0]) & (freqs < band[1])
    return float(np.mean(acc[m])) if m.any() else 1e-20


def scale_to_speech_band_snr(speech: np.ndarray, noise: np.ndarray, sr: float,
                             target_snr_db: float,
                             band=(50.0, 977.0)) -> np.ndarray:
    """Scale ``noise`` so that (speech-band power / noise-band power) =
    10**(target_snr/10), then return the scaled noise (same length as speech)."""
    sp = speech_band_power(speech, sr, band)
    np_ = speech_band_power(noise, sr, band)
    if np_ <= 0:
        return noise
    target_np = sp / (10.0 ** (target_snr_db / 10.0))
    scale = float(np.sqrt(target_np / np_))
    n = min(len(speech), len(noise))
    out = np.zeros_like(speech, dtype=np.float32)
    out[:n] = (noise[:n] * scale).astype(np.float32)
    return out


def add_noise(speech: np.ndarray, noise: np.ndarray, sr: float,
              target_snr_db: float, band=(50.0, 977.0)) -> np.ndarray:
    """Return speech + noise scaled to the target speech-band SNR."""
    scaled = scale_to_speech_band_snr(speech, noise, sr, target_snr_db, band)
    n = min(len(speech), len(scaled))
    out = speech.copy().astype(np.float32)
    out[:n] += scaled[:n]
    return out
